config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'

  resources :boards
  # devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }
  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }
  has_many :comments, dependent: :delete_all
  has_many :board_tag_relations, dependent: :delete_all
  has_many :tags, through: :board_tag_relations
end

app/models/board_tag_relation.rb
class BoardTagRelation < ApplicationRecord
  belongs_to :board
  belongs_to :tag 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :board

  validates :name, presence: true, length: {maximum: 10}
  validates :comment, presence: true, length: {maximum: 1000}
end

app/models/concerns/deletable.rb
module Deletable
  extend ActiveSupport::Concern

  included do
    validates :is_deleted, inclusion: { in: [true, false] }

    scope :not_deleted, -> { where(is_deleted: false) }
    scope :is_deleted, -> { where(is_deleted: true) }

    def deleted!
      update!(is_deleted: true)
    end

    def not_deleted!
      update!(is_deleted: false)
    end

    def not_deleted?
      !is_deleted?
    end
  end
end

app/models/concerns/encryptable.rb
module Encryptable
  extend ActiveSupport::Concern

  included do
    # 本当は環境変数にすべきだけど今更なのでハードコーディングしていくぅ
    ENCRYPTION_KEY = "\xA8W.\x12%\x7FRi\x888\xAE\xBD\xA3\xAC\xF3\xF3\x87\xEE\x11\xEE\xD5\xD1\xCBv/\x84\t\xE9\xAAO\xF0\n".freeze

    private

    def encryption_key
      ENCRYPTION_KEY
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :board_tag_relations, dependent: :delete_all
  has_many :boards, through: :board_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name,
    presence: true,
    uniqueness: true,
    length: { maximum: 16 }
    # format:  {
    #   with: /\A[a-zA-Z]+\z/,
    #   message: 'は小文字英数字で入力してください'
    # }
  validates :password,
    length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception, prepend: true

  private

  def configure_permitted_parameters
    added_attrs = %i[
      name
    ]

    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_target_board, only: %i[show edit update destroy]

  def index
    @boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    @boards = @boards.page(params[:page])
  end

  def new
    @board = Board.new(flash[:board])
  end

  def create
    board = Board.new(board_params)

    if board.save
      flash[:notice] = "「#{board.title}」の掲示板を作成しました"
      redirect_to board
    else
      flash[:board] = board
      flash[:error_messages] = board.errors.full_messages

      redirect_to new_board_path
    end
  end

  def show
    @comment = Comment.new(board_id: @board.id)
  end

  def edit
  end

  def update
    @board.update(board_params)

    redirect_to @board
  end

  def destroy    
    @board.destroy

    redirect_to boards_path, flash: { notice: "「#{@board.title}」の掲示板を作成しました" }

  end

  private 

  def board_params
    params.require(:board).permit(:name, :title, :body, tag_ids: [])
  end

  def set_target_board
    @board = Board.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:notice] = "コメントの作成に成功しました"
      redirect_to comment.board
    else
      flash[:comment] = comment
      flash[:error_messages] = comment.errors.full_messages

      redirect_to board_path(comment_params[:board_id])
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.delete
    redirect_to board_path(comment.board_id), flash: { notice: "コメントが削除されました" }
  end

  private

  def comment_params
    params.require(:comment).permit(:board_id, :name, :comment)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
  def show; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create

  end

  def me
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def jst(time)
    return unless time

    time.in_time_zone('Tokyo')
  end

  def header_link_item(name, path)
    class_name = 'nav-item'
    class_name << ' active' if current_page?(path)

    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end
  end
  
end

app/views/boards/_board.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= board.title %></h4>
    <% board.tags.each do |tag| %>
      <span class="badge badge-primary"><%= tag.name %></span>
    <% end %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(board.body) %></p>
    <p class="text-right font-weight-bold mr-10"><%= board.name %></p>
  </div>
</div>

app/views/boards/_comment.html.erb
<div class="p-comment__item">
  <p><%= simple_format(comment.comment) %></p>
  <div class="p-comment__bottomLine">
    <span><%= comment.name %></span>
    <span><%= comment.created_at.to_s(:datetime_jp) %></span>
    <span><%= link_to '削除', comment, method: :delete, data: { confirm: 'いっぺん押してみる？' } %></span>
  </div>
</div>

<style type="text/css">
  .p-comment__formBox {
    margin: 30px auto;
    border: 5px solid #e8e8e8;
    padding: 25px;
    border-radius: 14px;
  }

  .p-comment__formTitle {
    border-bottom: 2px solid #dfdfdf;
    padding-bottom: 5px;
  }

  .p-comment__listTitle {
    border-bottom: 2px solid #dfdfdf;
    padding-bottom: 5px;
  }

  .p-comment__list {
    margin: 38px 0;
    padding: 20px;
  }

  .p-comment__item {
    padding: 18px;
    border-bottom: 2px dotted #dfdfdf;
  }

  .p-comment__bottomLine {
    font-size: 15px;
    text-align: right;

    > span {
      font-size: 14px;
      margin: 0 12px;
    }
  }
</style>

app/views/boards/_form.html.erb
<%= render 'shared/error_messages'%>

<%= form_for board do |f| %>
  <div class="form-group">
    <%= f.label :name, '名前' %> 
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %> 
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, '本文' %> 
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>
  <div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板編集</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '掲示板一覧', boards_path, class: "btn btn-outline-dark" %>
  </div>
</div>
<%= render partial: "form", local: { board: @board }%>

app/views/boards/endex.html copy.slim
h1 掲示板テラフォーマーズ

app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板一覧</h1>
  <div class="ml-auto boards__linkBox">
    <%= form_tag boards_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                    options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                    {
                      prompt: 'タグで絞り込み',
                      class: 'form-control boards__select',
                      onchange: 'submit(this.form);'
                    }
      %>
    <% end %>
    <%= link_to '新規作成', new_board_path, class: "btn btn-outline-dark" %>
  </div>
</div>
<% if flash[:notice] %>
  <div class="alert alert-danger"><%= flash[:notice] %></div>
<% end %>
<table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.id %></td>
        <td><%= board.title %></td>
        <td><%= board.name + 'さん' %></td>
        <td><%= board.created_at.to_s(:datetime_jp) %></td>
        <td><%= board.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to '詳細', board_path(id: board.id), class: "btn btn-outline-dark"%></td>
        <td><%= link_to '削除', board_path(id: board.id), class: "btn btn-outline-dark", method: :delete, data: {confirm: '消すの？'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @boards %>

<style type="text/css">
  .boards__searchForm {
    display: inline-block;
  }

  .boards__select {
    display: inline-block;
    width: auto;
  }
</style>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '掲示板一覧', boards_path, class: "btn btn-outline-dark" %>
  </div>
</div>
<%= render partial: "form", locals: { board: @board } %>

app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: "btn btn-outline-dark" %>
    <%= link_to '編集', edit_board_path(@board), class: "btn btn-outline-dark" %>
  </div>
</div>

<% if flash[:notice] %>
  <div class="alert alert-primary"><%= flash[:notice] %></div>
<% end %>

<%= render partial: "board", object: @board %>

<div class="p-comment__list">
  <div class="p-comment_listTitle">コメント</div>
  <% @board.comments.each do |comment| %>
    <%= render 'comment', comment: comment %>
  <% end %>
</div>

<%= render partial: 'comments/form', locals: { comment: @comment } %>


<%
=begin%>
<%= render @board %>
<%
=end%>

app/views/comments/_form.html.erb
<%= render 'shared/error_messages'%>

<div class="p-comment__formBox">
  <p class="p-comment__formTitle">コメント記入</p>
  <%= form_for comment do |f| %>
    <%= f.hidden_field :board_id %>
    <div class="form-group">
      <%= f.label :name, '名前' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :comment, 'コメント' %>
      <%= f.text_area :comment, class: 'form-control', rows: 4 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
</div>

<style type="text/css">
  .p-comment__formBox {
    margin: 30px auto;
    border: 5px solid #e8e8e8;
    padding: 25px;
    border-radius: 14px;
  }

  .p-comment__formTitle {
    border-bottom: 2px solid #dfdfdf;
    padding-bottom: 5px;
  }
</style>

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/_flash.html.slim
- if flash.any?
  - flash.each do |key, val|
    - next if key == 'timedout'
    .js-navbar-alert.navbar-alert class="#{flash_class(key)}"
      = flash_message(val)
      = flash_close

- else
  .js-navbar-alert.navbar-alert style='display: none;'

app/views/layouts/_footer.html.slim
footer.footer.navbar.navbar-expand-md.navbar-light.bg-light
  .container-fluid
    #navbarNav.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        li.nav-item
          = link_to 'お問い合わせ',
            'https://www.unchi.com/unchi/contact',
            class: 'nav-link',
            target: :_blank,
            rel: 'noopener noreferrer'
        li.nav-item
          = link_to '特商法に基づく表記',
            'https://www.unchi.com/unchi/lp/tokusho',
            class: 'nav-link',
            target: :_blank,
            rel: 'noopener noreferrer'

        li.nav-item
          = link_to '利用規約',
            'https://www.unchi.com/unchi/terms',
            class: 'nav-link',
            target: :_blank,
            rel: 'noopener noreferrer'

        li.nav-item
          = link_to 'プライバシーポリシー',
            'https://www.unchi.com/unchi/privacy',
            class: 'nav-link',
            target: :_blank,
            rel: 'noopener noreferrer'

app/views/layouts/_head.html.slim
head
  meta charset='utf-8'
  meta http-equiv='X-UA-Compatible' content='IE=edge'
  meta name='viewport' content='width=device-width, initial-scale=1'
  title = [@title, ' テスト用に作った'].compact.join(' - ')

  title = content_for?(:title) ? yield(:title) : Rails.application.class.parent_name
  / = favicon_link_tag 'eShip_fc1.png'

  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag    'application', 'data-turbolinks-track': :reload, media: :all
  = javascript_include_tag 'application', 'data-turbolinks-track': :reload
  = javascript_include_tag '//kit.fontawesome.com/26c05a8f9a.js', crossorigin: :anonymous
  = javascript_include_tag '//js.stripe.com/v3/'
  / https://github.com/tuupola/lazyload
  = javascript_include_tag '//cdn.jsdelivr.net/npm/lazyload@2.0.0-rc.2/lazyload.js'

  link href='https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css' rel='stylesheet'
  script src='https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js'

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">BoardApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= header_link_item('Home', root_path) %>
      <%= header_link_item('Boards', boards_path) %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.slim
doctype html
html
  == render 'layouts/head'
  body
    == render 'layouts/header'
    / == render 'layouts/flash'
    .container-fluid.py-3 == yield
    / == render 'layouts/footer'

app/views/layouts/bk_application.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">BoardApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= header_link_item('ホーム', root_path) %>
      </li>
      <li class="nav-item">
        <%= header_link_item('掲示板一覧', boards_path) %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ユーザー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if @current_user %>
            <%= link_to 'マイページ', mypage_path, class: 'dropdown-item' %>
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
          <% else %>
            <%= link_to '登録', '', class: 'dropdown-item' %>
            <%= link_to 'ログイン', root_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/shared/_error_messages.html.erb
<% if flash[:error_messages] %>
  <div class="alert alert-danger">
    <ul>
      <% flash[:error_messages].each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/me.html.slim
h1 Users#me
p Find me in app/views/s/me.html.slim

app/views/users/new.html.slim
h1 Users#new
p Find me in app/views/users/new.html.slim